"""empty message

Revision ID: 003df6bcddfe
Revises: 68fdc02c5845
Create Date: 2021-07-07 00:04:28.485440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003df6bcddfe'
down_revision = '68fdc02c5845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
